const translations = {
    pt: {
        nav_about: "Sobre Mim",
        nav_portfolio: "Portfólio",
        drop_dashboard: "Dashboard",
        drop_ml: "Machine Learning",
        drop_dl: "Deep Learning",
        drop_genai: "GenAI",
        nav_home: "Início",
        nav_contact: "Contato",
        hero_title_1: "Olá, eu sou",
        hero_title_2: "Marcos C. Lisboa",
        hero_desc: "Os dados são a espada do século XXI, e quem conseguir manejá-los será o Samurai.",
        hero_hire: "Stack",
        hero_roles: "Cientista de Dados, Engenheiro de IA, Analista de Dados, Engenheiro de Dados",
        exp_badge: "Do insight à produção",
        proj_title: "Últimos Projetos",
        proj_all: "Todos os projetos",
        page_title_dashboard: "Projetos de Dashboard",
        page_title_ml: "Projetos de Machine Learning",
        page_title_dl: "Projetos de Deep Learning",
        page_title_genai: "Projetos de GenAI",
        footer_social: "Redes Sociais",
        footer_email: "Fale comigo",
        stack_title: "Tech Ecosystem",
        stack_subtitle: "Ferramentas que impulsionam o impacto de dados",
        sobre_title: "O Propósito",
        sobre_desc: "Cientista de Dados movido pela curiosidade e focado na transformação de informações brutas em soluções estratégicas. Descubro as histórias escondidas nos números para apoiar decisões de alto valor e gerar impacto real.",
        sobre_arsenal: "O Arsenal Técnico",
        sobre_arsenal_desc: "Combino programação avançada, estatística e modelagem preditiva para responder às perguntas complexas de negócios de ponta a ponta.",
        sobre_alem: "Além dos Dados",
        sobre_alem_desc: "Mantenho fortemente o equilíbrio entre a vida tech, esportes, música e literatura. São essas as experiências plurais que oxigenam meu design e garantem a criatividade profissional.",
        proj_pred: "Predição de Séries Temporais",
        proj_recom: "Sistema de Recomendação",
        proj_fraud: "Detecção de Fraude (Random Forest)",
        proj_med: "Classificação de Imagens Médicas",
        proj_nlp: "Processamento de Linguagem Natural",
        proj_rag: "Sistema RAG p/ Documentos",
        proj_assist: "Assistente Virtual Corporativo",
        
        // Dashboards
        dash_trade_title: "📈 Trade Marketing Analytics",
        dash_trade_subtitle: "Varejo & E-commerce | Trade Mania",
        dash_trade_desc: "Painel completo de análise de PDVs com foco em disponibilidade, índice de ruptura e monitoramento de preços médios por região.",
        dash_trade_feat1: "Disponibilidade e índice de ruptura.",
        dash_trade_feat2: "Preço Médio comparativo por estado.",
        dash_trade_feat3: "Performance da equipe de promotores.",

        dash_health_title: "🩺 Health Data Analytics",
        dash_health_subtitle: "Sinistros Hospitalares | Performance de Planos",
        dash_health_desc: "Monitoramento completo de custos de sinistros com planos de saúde, performance de autorizações e análise de coparticipação e procedimentos médicos.",
        dash_health_feat1: "Controle Financeiro sobre R$ 108 mil em procedimentos.",
        dash_health_feat2: "Eficiência com taxa de aprovação geral de 95%.",
        dash_health_feat3: "Sazonalidade para antecipação de custos de saúde.",

        dash_logistics_title: "🌍 Logistics & Supply Chain",
        dash_logistics_subtitle: "Performance Macro • Rentabilidade • Riscos",
        dash_logistics_desc: "Monitoramento global da cadeia de suprimentos, analisando o crescimento de vendas (R$ 12.6 Mi) e eficiência de entrega.",
        dash_logistics_feat1: "Performance Macro: Volume e rentabilidade por região.",
        dash_logistics_feat2: "Alerta de Prejuízo: Detecção de gargalos logísticos.",
        dash_logistics_feat3: "Sustentação de Lucro: Foco em clientes de alto CLV.",

        dash_ecommerce_title: "🛒 E-commerce Analytics",
        dash_ecommerce_subtitle: "Vendas • Performance • Produtos",
        dash_ecommerce_desc: "Painel de monitoramento de vendas online, faturamento, ticket médio e performance de produtos e categorias.",
        dash_ecommerce_feat1: "Faturamento: Análise de receita e ticket médio.",
        dash_ecommerce_feat2: "Produtos: Top produtos e categorias mais vendidas.",
        dash_ecommerce_feat3: "Clientes: Comportamento e retenção de usuários.",

        // Web Dashboards - Trade
        trade_web_title: "Painel de Disponibilidade e Ruptura",
        trade_web_subtitle: "Análisis de cobertura de PDV, evolução de rupturas e preços promedio",
        trade_web_kpi1: "Disponibilidade Geral",
        trade_web_kpi2: "Ruptura Promedio",
        trade_web_kpi3: "Visitas Realizadas",
        trade_web_kpi4: "PDV Visitados",
        trade_web_kpi5: "Preço Médio Geral",
        trade_web_kpi6: "Total de Produtos",
        trade_web_chart_desc1: "Queda gradual após pico em agosto → setembro/outubro com melhora",
        trade_web_chart_desc2: "Chocolate 60% e Barra lideram indisponibilidades",
        trade_web_chart_desc3: "Variação de até 70% acima da média geral",
        trade_web_top_pdv: "PDVs com maior preço médio",
        trade_web_performance_title: "Performance por Promotor (Ruptura %)",
        trade_web_insight_1: "Rupturas caíram de 125 (ago) para 96 (out) – tendência positiva, mas ainda alta em chocolates (60% e barra).",
        trade_web_insight_2: "Variação de preço entre estados: RJ (R$6,60) &gt; MG (R$6,35) &gt; SP (R$6,11). Rever política de preços para equalizar competitividade.",
        trade_web_recom_title: "Recomendações Estratégicas",
        trade_web_recom_1: "Meta disponibilidade &gt;70%",
        trade_web_recom_2: "Treinar promotores críticos",
        trade_web_recom_3: "Revisar preços por UF",
        trade_web_next_steps: "Próximos passos:",
        trade_web_next_desc: "Foco em chocolate 60% e barras (80% das rupturas). Auditoria nos PDVs com &gt;70% de ruptura. Equalizar preço médio entre RJ e SP para reduzir canibalização.",

        // Web Dashboards - Health
        health_web_title: "Health Data Analytics",
        health_web_subtitle: "Visão Operadora • Gestão de Autorização de Sinistros",
        health_web_filter: "Filtrando por:",
        health_web_kpi1: "Taxa Aprovação",
        health_web_kpi1_sub: "Desvio mínimo de aprovação",
        health_web_kpi2: "Valor Total Autorizado",
        health_web_kpi2_sub: "Distribuído em 22 guias",
        health_web_kpi3: "Custo Médio Cirúrgico",
        health_web_kpi3_sub: "Atenção Crítica: Principal Ofensor",
        health_web_kpi4: "Economia/Redução",
        health_web_kpi4_sub: "Em 3 guias reduzidas (~27%)",
        health_web_chart1: "Valor Autorizado por Mês",
        health_web_chart2: "Distribuição Custos por Plano",
        health_web_chart3: "Gastos por Categoria de Procedimento",
        health_web_chart4: "Quebra de Custo por Usuário",
        health_web_insight_title: "Insights & Ações Estratégicas",
        health_web_discovery: "Principais Descobertas:",
        health_web_insight_1: "<strong>Tendências Gasto:</strong> Boa taxa de aprovação, mas atentar as pequenas reduções de custos e investigar o motivo. Melhorando o processo.",
        health_web_insight_2: "<strong>Procedimentos e Prestadores:</strong> \"Procedimentos Cirúrgicos\" são os maiores ofensores. Monitorar de perto Hospital Santa Cruz e Clínica Checkup.",
        health_web_insight_3: "<strong>Avaliação de Usuários Críticos:</strong> O beneficiário 'Carlos Souza' representa o maior custo isolado. Casos complexos exigem acompanhamento de saúde dedicado.",
        health_web_action: "Plano de Ação Recomendado:",
        health_web_recom_1_title: "Auditoria Focada em Cirurgias",
        health_web_recom_1_desc: "Concentrar a auditoria técnica de saúde sobre os pedidos de cirurgia dos maiores prestadores.",
        health_web_recom_2_title: "Gestão de Casos Críticos",
        health_web_recom_2_desc: "Criar comitê para usuários em uso contínuo/complexo como o paciente 'Carlos Souza'.",
        health_web_recom_3_title: "Análise de Negativas/Reduções",
        health_web_recom_3_desc: "Revisar padrões de glosas e buscar conciliação pró-ativa com clínicas.",

        // Web Dashboards - Logistics
        logistics_web_title: "Logistics & Supply Chain Analytics",
        logistics_web_subtitle: "Performance Macro • Rentabilidade • Riscos",
        logistics_web_kpi1: "Receita Total",
        logistics_web_kpi2: "Margem de Lucro",
        logistics_web_kpi3: "Tempo Médio Envio",
        logistics_web_kpi4: "Qtd. Vendas (Volume)",
        logistics_web_chart1: "Evolução de Vendas Anuais",
        logistics_web_chart2: "Receita por Categoria de Produto",
        logistics_web_chart3: "Dominância Regional",
        logistics_web_chart4: "Alerta de Prejuízo (Detratores)",
        logistics_web_insight_title: "Conclusões Estratégicas",
        logistics_web_discovery_title: "Painéis Integrados:",
        logistics_web_insight_1: "<strong>Mercado e Consumidor:</strong> \"Consumer\" representa a maior fatia do faturamento. Operação B2C massiva e pulverizada.",
        logistics_web_insight_2: "<strong>Estrelas vs. Detratores:</strong> Equipamentos de alta tecnologia (Copiadoras/Smartphones) sustentam lucro. Mesas e Scanners grandes geram gargalos no frete.",
        logistics_web_insight_3: "<strong>Concentração de Valor:</strong> Aplicada a regra de Pareto aos 10 principais clientes – necessidade de proteger o Customer Lifetime Value (CLV).",
        logistics_web_action_title: "Próximos Desafios:",
        logistics_web_recom_1_title: "Otimização do Mix (Bottom 10)",
        logistics_web_recom_1_desc: "Revisão para itens onde o frete é ofensor: considerar estoques locais ou ajuste no preço de envio.",
        logistics_web_recom_2_title: "Foco na APAC",
        logistics_web_recom_2_desc: "Consolidar investimentos na Ásia-Pacífico, que apresenta a melhor relação entre volume e margem.",
        logistics_web_recom_3_title: "Gestão de Grandes Contas",
        logistics_web_recom_3_desc: "Atendimento diferenciado para os clientes de topo identificados, garantindo a recorrência do lucro de alta margem.",

        // Web Dashboards - Ecommerce
        ecom_web_tab1: "📊 Análise de Vendas",
        ecom_web_tab2: "🌍 Visão Geográfica",
        ecom_web_kpi_profit: "Lucro",
        ecom_web_chart1: "Vendas Mensal",
        ecom_web_chart2: "Custo Envio por Cliente",
        ecom_web_chart3: "Venda por Cliente",
        ecom_web_insight_title: "Insights & Ações Estratégicas",
        ecom_web_discovery: "Principais Descobertas:",
        ecom_web_insight_1: "<strong>Sazonalidade Positiva:</strong> As vendas crescem consideravelmente no segundo semestre de cada ano, indicando sucesso contínuo nas campanhas de final de ano.",
        ecom_web_insight_2: "<strong>Custo de Frete Alto:</strong> Certos clientes do segmento Consumidor e Corporativo geram custos logísticos elevados que reduzem a margem de lucro.",
        ecom_web_insight_3: "<strong>Produtos Críticos:</strong> As categorias de vendas críticas possuem baixo lucro líquido comparado ao volume transacionado.",
        ecom_web_action: "Plano de Ação Recomendado:",
        ecom_web_recom_1_title: "Preparação para o Q4",
        ecom_web_recom_1_desc: "Ancorar estoque e campanhas massivas de marketing entre Outubro e Dezembro para maximizar a receita de alta temporada.",
        ecom_web_recom_2_title: "Auditoria Logística",
        ecom_web_recom_2_desc: "Analisar as rotas de envio com maiores custos e renegociar tarifas ou estipular valor mínimo para frete grátis.",
        ecom_web_recom_3_title: "Fidelização B2C",
        ecom_web_recom_3_desc: "Lançar programa de recompensas focado no segmento de Consumidores (que é majoritário) para estimular o ticket médio.",
        ecom_web_kpi_sales: "Vendas",
        ecom_web_kpi_orders: "Pedidos Gerados",
        ecom_web_kpi_products: "Total Produtos",
        ecom_web_kpi_sales_vol: "Total Vendas Realizadas",
        ecom_web_kpi_customers: "Clientes",
        ecom_web_chart_state: "Contagem de Pedido por Estado",
        ecom_web_chart_city: "Contagem de Pedido por Cidade",
        ecom_web_chart_country: "Vendas por País",
        ecom_web_th_country: "País",
        ecom_web_th_state: "Estado",
        ecom_web_th_city: "Cidade",
        ecom_web_th_profit: "Soma de Lucro",
        ecom_web_th_sales_val: "Soma de Valor Venda",
        ecom_web_th_qty: "Qtd.",
        ecom_web_filter_all: "Todos",
        ecom_web_filter_high: "Alto",
        ecom_web_filter_low: "Baixo",
        ecom_web_filter_critical: "Crítico",
        ecom_web_filter_medium: "Médio",
        ecom_web_filter_consumer: "Consumidor",
        ecom_web_filter_corporate: "Corporativo",
        ecom_web_filter_others: "Outros",
        ecom_web_filter_office: "Mat. de Escrit.",
        ecom_web_filter_furniture: "Móveis",
        ecom_web_filter_tech: "Tecnologia",
        ecom_web_filter_prior: "Prioridade Pedido",
        ecom_web_filter_seg: "Segmento",
        ecom_web_filter_cat: "Categoria",
        ecom_web_filter_year: "Ano",
        global_days: "dias",
        global_thousand: "Mil",
        global_filtering_by: "Filtrando por:",
        trade_web_kpi1_sub: "abaixo do ideal",
        trade_web_kpi2_sub: "média por visita",
        trade_web_kpi3_sub: "total no período",
        trade_web_kpi4_sub: "cobertura total",
        trade_web_kpi5_sub: "variação:",
        trade_web_kpi6_sub: "checados nas visitas",
        logistics_web_kpi4_val: "178 Mil",
        health_web_jan_may: "Jan-Mai 2024",

        // Trade dashboard extras
        trade_web_insight_0: "Disponibilidade geral em <strong>43,6%</strong> – muito abaixo do ideal. Aumentar para ≥70% pode gerar +30% em vendas nos PDVs.",
        trade_web_th_promoter: "Promotor",
        trade_web_th_stockout: "Ruptura (%)",
        trade_web_th_status: "Status",
        trade_web_status_critical: "crítico",
        trade_web_status_alert: "alerta",
        trade_web_status_warning: "atenção",
        trade_web_status_ok: "ok",
        trade_web_training_tip: "📌 Treinamento focado nos 3 promotores pode reduzir ruptura geral em até 0,2 p.p.",
        trade_web_pdv_sample_title: "Ruptura por PDV (%) – Amostra",
        trade_web_sample_note: "*Dados baseados nas capturas de tela – ruptura superior a 50% indica falha crítica de abastecimento.",

        // Health dashboard extras
        health_web_th_user: "Nome do Usuário",
        health_web_th_state: "UF",
        health_web_th_authorized: "Valor Autorizado",
        health_web_th_reduced: "Valor Reduzido",

        // Logistics dashboard extras
        logistics_web_kpi1_sub: "Trajetória de Crescimento Exponencial",
        logistics_web_kpi2_sub: "Estabilidade Comprovada",
        logistics_web_kpi3_sub: "Benchmark Logístico",
        logistics_web_kpi4_sub: "Agilidade em Alto Volume",
        logistics_web_detractors_note: "Custos operacionais e logísticos superam margem.",
        logistics_web_th_product: "Produto / Subcategoria",
        logistics_web_th_cost_type: "Tipo de Custo Elevado",
        logistics_web_th_margin: "Margem Líquida",
        logistics_prod_1: "Mesas e Equip. Pesados",
        logistics_prod_2: "Impressoras 3D Específicas",
        logistics_prod_3: "Scanners de Grande Porte",
        logistics_prod_4: "Cadeiras Executivas",
        logistics_cost_1: "Frete Extra",
        logistics_cost_2: "Custo Operacional",
        logistics_cost_3: "Frete + Descontos",
        logistics_cost_4: "Frete Volumoso",

        // Fraud ML Project
        proj_fraud_ml_title: "💳 Detecção de Fraudes",
        proj_fraud_ml_subtitle: "Machine Learning em Transações Financeiras",
        proj_fraud_ml_desc: "Desenvolvimento de modelo preditivo para detecção de fraudes em cartões de crédito, utilizando técnicas de balanceamento (RUS), tuning de hiperparâmetros e otimização de threshold para impacto de negócio.",
        proj_fraud_ml_results: "84% de Detecção • AUC 0.97",
        proj_fraud_ml_problem_title: "Problema de Negócio",
        proj_fraud_ml_problem_text: "Fraudes em cartões representam um risco crítico. O desafio é classificar transações em um cenário altamente desbalanceado, onde fraudes são menos de 1% do total, minimizando prejuízos financeiros.",
        proj_fraud_ml_objective_title: "Objetivo",
        proj_fraud_ml_objective_text: "Construir um pipeline robusto capaz de detectar transações fraudulentas com alto recall, minimizar falsos negativos e otimizar o threshold de decisão com foco em impacto de negócio.",
        proj_fraud_ml_pipeline_title: "Pipeline de Machine Learning",
        proj_fraud_ml_metrics_title: "Métricas de Avaliação",
        proj_fraud_ml_impact_title: "Impacto no Negócio",
        proj_fraud_ml_impact_text: "Transição da detecção reativa para a proativa, permitindo a redução de perdas financeiras e o ajuste de sensibilidade baseado na tolerância ao risco da instituição.",
        proj_fraud_ml_tech: "Python • Scikit-learn • Pandas • Matplotlib",
        proj_fraud_ml_dataset_title: "📊 Dataset",
        proj_fraud_ml_dataset_text: "Dataset de transações reais (clientes europeus) com 284.807 registros e apenas 492 fraudes (~0.17%). Features transformadas via PCA.",
        proj_fraud_ml_pipeline_step1: "1. Pré-processamento",
        proj_fraud_ml_pipeline_desc1: "Normalização e padronização de variáveis temporais e financeiras via StandardScaler.",
        proj_fraud_ml_pipeline_step2: "2. Balanceamento",
        proj_fraud_ml_pipeline_desc2: "Análise rigorosa de técnicas de balanceamento: Random Under Sampling (RUS) vs SMOTE.",
        proj_fraud_ml_pipeline_step3: "3. Modelagem",
        proj_fraud_ml_pipeline_desc3: "Regressão Logística e Árvores de Decisão com tuning de hiperparâmetros.",
        proj_fraud_ml_impact_kpi: "Proativo",
        proj_fraud_ml_github: "Ver no GitHub",
        proj_fraud_ml_other_desc1: "Análise de tendências históricas e previsão de demanda futura.",
        proj_fraud_ml_other_desc2: "Filtragem colaborativa para personalização de experiência.",
        explorer_title_tag: "Continue Explorando",
        explorer_title_main: "Outros Projetos de Machine Learning",
        explorer_dash_title: "Business Dashboards",
        explorer_dash_desc: "Visualização estratégica de dados e KPIs de negócio.",
        card_btn_details: "Ver detalhes",
        card_btn_view: "Ver dashboard",
        footer_rights: "© 2024 MARCOS C. LISBOA • DATA SCIENCE & ML EXECUTIVE",
    },
    en: {
        nav_about: "About Me",
        nav_portfolio: "Portfolio",
        drop_dashboard: "Dashboard",
        drop_ml: "Machine Learning",
        drop_dl: "Deep Learning",
        drop_genai: "GenAI",
        nav_home: "Home",
        nav_contact: "Contact Me",
        hero_title_1: "Hello, I am",
        hero_title_2: "Marcos C. Lisboa",
        hero_desc: "Data is the sword of the 21st century, and whoever can wield it will be the Samurai.",
        hero_hire: "Stack",
        hero_roles: "Data Scientist, AI Engineer, Data Analyst, Data Engineer",
        exp_badge: "From insight to production",
        proj_title: "Latest Projects",
        proj_all: "All projects",
        page_title_dashboard: "Dashboard Projects",
        page_title_ml: "Machine Learning Projects",
        page_title_dl: "Deep Learning Projects",
        page_title_genai: "GenAI Projects",
        footer_social: "Social Networks",
        footer_email: "Talk to me",
        stack_title: "Tech Ecosystem",
        stack_subtitle: "Tools that drive data impact",
        sobre_title: "The Purpose",
        sobre_desc: "Data Scientist driven by curiosity and focused on transforming raw information into strategic solutions. I uncover the hidden stories in numbers to support high-value decisions and generate real impact.",
        sobre_arsenal: "Technical Arsenal",
        sobre_arsenal_desc: "I combine advanced programming, statistics, and predictive modeling to answer complex end-to-end business questions.",
        sobre_alem: "Beyond Data",
        sobre_alem_desc: "I strongly maintain the balance between tech life, sports, music, and literature. Those plural experiences oxygenate my design and ensure professional creativity.",
        proj_pred: "Time Series Prediction",
        proj_recom: "Recommendation System",
        proj_fraud: "Fraud Detection (Random Forest)",
        proj_yolo: "Object Detection (YOLOv8)",
        proj_med: "Medical Image Classification",
        proj_nlp: "Natural Language Processing",
        proj_rag: "RAG System for Documents",
        proj_assist: "Corporate Virtual Assistant",

        // Dashboards
        dash_trade_title: "📈 Trade Marketing Analytics",
        dash_trade_subtitle: "Retail & E-commerce | Trade Mania",
        dash_trade_desc: "Complete POS analysis dashboard focusing on availability, out-of-stock rates, and average price monitoring by region.",
        dash_trade_feat1: "Availability and out-of-stock index.",
        dash_trade_feat2: "Comparative Average Price by state.",
        dash_trade_feat3: "Promoter team performance.",

        dash_health_title: "🩺 Health Data Analytics",
        dash_health_subtitle: "Hospital Claims | Plan Performance",
        dash_health_desc: "Complete monitoring of health plan claim costs, authorization performance, and analysis of co-payments and medical procedures.",
        dash_health_feat1: "Financial Control over R$ 108k in procedures.",
        dash_health_feat2: "Efficiency with a 95% overall approval rate.",
        dash_health_feat3: "Seasonality for health cost anticipation.",

        dash_logistics_title: "🌍 Logistics & Supply Chain",
        dash_logistics_subtitle: "Macro Performance • Profitability • Risks",
        dash_logistics_desc: "Global supply chain monitoring, analyzing sales growth (R$ 12.6 Mi) and shipping efficiency.",
        dash_logistics_feat1: "Macro Performance: Volume and profitability by region.",
        dash_logistics_feat2: "Loss Alert: Detection of logistical bottlenecks.",
        dash_logistics_feat3: "Profit Sustenance: Focus on high CLV customers.",

        dash_ecommerce_title: "🛒 E-commerce Analytics",
        dash_ecommerce_subtitle: "Sales • Performance • Products",
        dash_ecommerce_desc: "Online sales monitoring dashboard, revenue, average ticket, and product/category performance.",
        dash_ecommerce_feat1: "Revenue: Analysis of revenue and average ticket.",
        dash_ecommerce_feat2: "Products: Top products and best-selling categories.",
        dash_ecommerce_feat3: "Customers: User behavior and retention.",

        // Web Dashboards - Health
        health_web_title: "Health Data Analytics",
        health_web_subtitle: "Operator View • Claim Authorization Management",
        health_web_filter: "Filtering by:",
        health_web_kpi1: "Approval Rate",
        health_web_kpi1_sub: "Minimal approval deviation",
        health_web_kpi2: "Total Authorized Value",
        health_web_kpi2_sub: "Distributed across 22 claims",
        health_web_kpi3: "Avg Surgical Cost",
        health_web_kpi3_sub: "Critical Attention: Main Offender",
        health_web_kpi4: "Savings/Reduction",
        health_web_kpi4_sub: "In 3 reduced claims (~27%)",
        health_web_chart1: "Authorized Value per Month",
        health_web_chart2: "Cost Distribution per Plan",
        health_web_chart3: "Spending per Procedure Category",
        health_web_chart4: "Cost Breakdown per User",
        health_web_insight_title: "Insights & Strategic Actions",
        health_web_discovery: "Main Discoveries:",
        health_web_insight_1: "<strong>Spending Trends:</strong> Good approval rate, but pay attention to small cost reductions and investigate the reason. Improving the process.",
        health_web_insight_2: "<strong>Procedures and Providers:</strong> \"Surgical Procedures\" are the biggest offenders. Closely monitor Santa Cruz Hospital and Checkup Clinic.",
        health_web_insight_3: "<strong>Critical User Assessment:</strong> Beneficiary 'Carlos Souza' represents the highest isolated cost. Complex cases require dedicated health monitoring.",
        health_web_action: "Recommended Action Plan:",
        health_web_recom_1_title: "Surgical-Focused Audit",
        health_web_recom_1_desc: "Concentrate technical health audit on surgical requests from the largest providers.",
        health_web_recom_2_title: "Critical Case Management",
        health_web_recom_2_desc: "Create a committee for continuous/complex use users such as patient 'Carlos Souza'.",
        health_web_recom_3_title: "Negative/Reduction Analysis",
        health_web_recom_3_desc: "Review claim denial patterns and seek proactive reconciliation with clinics.",

        // Web Dashboards - Trade
        trade_web_title: "Availability & Out-of-stock Dashboard",
        trade_web_subtitle: "POS coverage analysis, stockout trends and average prices",
        trade_web_kpi1: "General Availability",
        trade_web_kpi2: "Average Stockout",
        trade_web_kpi3: "Visits Performed",
        trade_web_kpi4: "Visited POS",
        trade_web_kpi5: "General Avg Price",
        trade_web_kpi6: "Total Products",
        trade_web_chart1: "Unavailable Products (trend)",
        trade_web_chart2: "Stockouts per Category (units)",
        trade_web_chart3: "Average Price per State",
        trade_web_chart_desc1: "Gradual decline after peak in August → September/October with improvement",
        trade_web_chart_desc2: "60% Chocolate and Bar lead unavailability",
        trade_web_chart_desc3: "Variation of up to 70% above the general average",
        trade_web_top_pdv: "POS with highest average price",
        trade_web_performance_title: "Performance by Promoter (Stockout %)",
        trade_web_insight_1: "Stockouts dropped from 125 (Aug) to 96 (Oct) – positive trend, but still high in chocolates (60% and bar).",
        trade_web_insight_2: "Price variation between states: RJ (R$6.60) > MG (R$6.35) > SP (R$6.11). Review pricing policy to equalize competitiveness.",
        trade_web_recom_title: "Strategic Recommendations",
        trade_web_recom_1: "Target availability >70%",
        trade_web_recom_2: "Train critical promoters",
        trade_web_recom_3: "Review prices by State",
        trade_web_next_steps: "Next steps:",
        trade_web_next_desc: "Focus on 60% chocolate and bars (80% of stockouts). Audit POS with >70% stockout. Equalize average price between RJ and SP to reduce cannibalization.",

        // Web Dashboards - Logistics
        logistics_web_title: "Logistics & Supply Chain Analytics",
        logistics_web_subtitle: "Macro Performance • Profitability • Risks",
        logistics_web_kpi1: "Total Revenue",
        logistics_web_kpi2: "Profit Margin",
        logistics_web_kpi3: "Avg Shipping Time",
        logistics_web_kpi4: "Sales Qty (Volume)",
        logistics_web_chart1: "Annual Sales Evolution",
        logistics_web_chart2: "Revenue by Product Category",
        logistics_web_chart3: "Regional Dominance",
        logistics_web_chart4: "Profit Loss Alert (Detractors)",
        logistics_web_insight_title: "Strategic Conclusions",
        logistics_web_discovery_title: "Integrated Dashboards:",
        logistics_web_insight_1: "<strong>Market and Consumer:</strong> \"Consumer\" represents the largest share of revenue. Massive and fragmented B2C operation.",
        logistics_web_insight_2: "<strong>Stars vs. Detractors:</strong> High-tech equipment (Copiers/Smartphones) sustain profit. Large Tables and Scanners generate shipping bottlenecks.",
        logistics_web_insight_3: "<strong>Value Concentration:</strong> Pareto rule applied to the top 10 clients – need to protect Customer Lifetime Value (CLV).",
        logistics_web_action_title: "Next Challenges:",
        logistics_web_recom_1_title: "Mix Optimization (Bottom 10)",
        logistics_web_recom_1_desc: "Review for items where shipping is an offender: consider local stocks or shipping price adjustments.",
        logistics_web_recom_2_title: "Focus on APAC",
        logistics_web_recom_2_desc: "Consolidate investments in Asia-Pacific, which presents the best ratio between volume and margin.",
        logistics_web_recom_3_title: "Key Account Management",
        logistics_web_recom_3_desc: "Differentiated service for identified top clients, ensuring high-margin profit recurrence.",

        // Web Dashboards - Ecommerce
        ecom_web_tab1: "📊 Sales Analysis",
        ecom_web_tab2: "🌍 Geographic View",
        ecom_web_kpi_profit: "Profit",
        ecom_web_chart1: "Monthly Sales",
        ecom_web_chart2: "Shipping Cost per Customer",
        ecom_web_chart3: "Sales per Customer",
        ecom_web_insight_title: "Insights & Strategic Actions",
        ecom_web_discovery: "Main Discoveries:",
        ecom_web_insight_1: "<strong>Positive Seasonality:</strong> Sales grow considerably in the second half of each year, indicating continued success in year-end campaigns.",
        ecom_web_insight_2: "<strong>High Shipping Cost:</strong> Certain Consumer and Corporate segment customers generate high logistical costs that reduce profit margin.",
        ecom_web_insight_3: "<strong>Critical Products:</strong> Critical sales categories have low net profit compared to the transacted volume.",
        ecom_web_action: "Recommended Action Plan:",
        ecom_web_recom_1_title: "Q4 Preparation",
        ecom_web_recom_1_desc: "Anchor stock and massive marketing campaigns between October and December to maximize peak season revenue.",
        ecom_web_recom_2_title: "Logistical Audit",
        ecom_web_recom_2_desc: "Analyze shipping routes with highest costs and renegotiate rates or set minimum value for free shipping.",
        ecom_web_recom_3_title: "B2C Loyalty",
        ecom_web_recom_3_desc: "Launch rewards program focused on the Consumer segment (which is majority) to stimulate average ticket.",
        ecom_web_kpi_sales: "Sales",
        ecom_web_kpi_orders: "Orders Generated",
        ecom_web_kpi_products: "Total Products",
        ecom_web_kpi_sales_vol: "Total Sales Volume",
        ecom_web_kpi_customers: "Customers",
        ecom_web_chart_state: "Order Count by State",
        ecom_web_chart_city: "Order Count by City",
        ecom_web_chart_country: "Sales by Country",
        ecom_web_th_country: "Country",
        ecom_web_th_state: "State",
        ecom_web_th_city: "City",
        ecom_web_th_profit: "Total Profit",
        ecom_web_th_sales_val: "Total Sales Value",
        ecom_web_th_qty: "Qty",
        ecom_web_filter_all: "All",
        ecom_web_filter_high: "High",
        ecom_web_filter_low: "Low",
        ecom_web_filter_critical: "Critical",
        ecom_web_filter_medium: "Medium",
        ecom_web_filter_consumer: "Consumer",
        ecom_web_filter_corporate: "Corporate",
        ecom_web_filter_others: "Others",
        ecom_web_filter_office: "Office Supplies",
        ecom_web_filter_furniture: "Furniture",
        ecom_web_filter_tech: "Technology",
        ecom_web_filter_prior: "Order Priority",
        ecom_web_filter_seg: "Segment",
        ecom_web_filter_cat: "Category",
        ecom_web_filter_year: "Year",
        global_days: "days",
        global_thousand: "k",
        global_filtering_by: "Filtering by:",
        trade_web_kpi1_sub: "below ideal",
        trade_web_kpi2_sub: "average per visit",
        trade_web_kpi3_sub: "total in period",
        trade_web_kpi4_sub: "total coverage",
        trade_web_kpi5_sub: "variation:",
        trade_web_kpi6_sub: "checked in visits",
        logistics_web_kpi4_val: "178k",
        health_web_jan_may: "Jan-May 2024",

        // Trade dashboard extras
        trade_web_insight_0: "Overall availability at <strong>43.6%</strong> – far below ideal. Raising to ≥70% can generate +30% in POS sales.",
        trade_web_th_promoter: "Promoter",
        trade_web_th_stockout: "Stockout (%)",
        trade_web_th_status: "Status",
        trade_web_status_critical: "critical",
        trade_web_status_alert: "alert",
        trade_web_status_warning: "warning",
        trade_web_status_ok: "ok",
        trade_web_training_tip: "📌 Training focused on the 3 promoters can reduce overall stockout by up to 0.2 p.p.",
        trade_web_pdv_sample_title: "Stockout by POS (%) – Sample",
        trade_web_sample_note: "*Data based on screenshots – stockout above 50% indicates a critical supply failure.",

        // Health dashboard extras
        health_web_th_user: "User Name",
        health_web_th_state: "State",
        health_web_th_authorized: "Authorized Amount",
        health_web_th_reduced: "Reduced Amount",

        // Logistics dashboard extras
        logistics_web_kpi1_sub: "Exponential Growth Trajectory",
        logistics_web_kpi2_sub: "Proven Stability",
        logistics_web_kpi3_sub: "Logistics Benchmark",
        logistics_web_kpi4_sub: "Agility at High Volume",
        logistics_web_detractors_note: "Operational and logistics costs exceed margin.",
        logistics_web_th_product: "Product / Subcategory",
        logistics_web_th_cost_type: "High Cost Type",
        logistics_web_th_margin: "Net Margin",
        logistics_prod_1: "Heavy Tables & Equipment",
        logistics_prod_2: "Specific 3D Printers",
        logistics_prod_3: "Large-Format Scanners",
        logistics_prod_4: "Executive Chairs",
        logistics_cost_1: "Extra Freight",
        logistics_cost_2: "Operational Cost",
        logistics_cost_3: "Freight + Discounts",
        logistics_cost_4: "Bulky Freight",

        // Fraud ML Project
        proj_fraud_ml_title: "💳 Fraud Detection",
        proj_fraud_ml_subtitle: "Machine Learning in Financial Transactions",
        proj_fraud_ml_desc: "Development of a predictive model for credit card fraud detection, using balancing techniques (RUS), hyperparameter tuning, and threshold optimization for business impact.",
        proj_fraud_ml_results: "84% Detection • AUC 0.97",
        proj_fraud_ml_problem_title: "Business Problem",
        proj_fraud_ml_problem_text: "Credit card fraud represents a critical risk. The challenge is to classify transactions in a highly imbalanced scenario, where fraud is less than 1% of the total, while minimizing financial losses.",
        proj_fraud_ml_objective_title: "Objective",
        proj_fraud_ml_objective_text: "Build a robust pipeline to detect fraudulent transactions with high recall, minimize false negatives, and optimize the decision threshold with a focus on business impact.",
        proj_fraud_ml_pipeline_title: "Machine Learning Pipeline",
        proj_fraud_ml_metrics_title: "Evaluation Metrics",
        proj_fraud_ml_impact_title: "Business Impact",
        proj_fraud_ml_impact_text: "Transition from reactive to proactive detection, allowing for reduced financial losses and sensitivity adjustment based on the institution's risk tolerance.",
        proj_fraud_ml_tech: "Python • Scikit-learn • Pandas • Matplotlib",
        proj_fraud_ml_dataset_title: "📊 Dataset",
        proj_fraud_ml_dataset_text: "Real transaction dataset (European cardholders) with 284,807 records and only 492 fraud cases (~0.17%). Features transformed via PCA.",
        proj_fraud_ml_pipeline_step1: "1. Preprocessing",
        proj_fraud_ml_pipeline_desc1: "Normalization and standardization of temporal and financial variables via StandardScaler.",
        proj_fraud_ml_pipeline_step2: "2. Balancing",
        proj_fraud_ml_pipeline_desc2: "Rigorous analysis of balancing techniques: Random Under Sampling (RUS) vs SMOTE.",
        proj_fraud_ml_pipeline_step3: "3. Modeling",
        proj_fraud_ml_pipeline_desc3: "Logistic Regression and Decision Trees with hyperparameter tuning.",
        proj_fraud_ml_impact_kpi: "Proactive",
        proj_fraud_ml_github: "View on GitHub",
        proj_fraud_ml_other_desc1: "Analysis of historical trends and forecasting of future demand.",
        proj_fraud_ml_other_desc2: "Collaborative filtering for personalized user experience.",
        explorer_title_tag: "Keep Exploring",
        explorer_title_main: "Other Machine Learning Projects",
        explorer_dash_title: "Business Dashboards",
        explorer_dash_desc: "Strategic data visualization and business KPIs.",
        card_btn_details: "View details",
        card_btn_view: "View dashboard",
        footer_rights: "© 2024 MARCOS C. LISBOA • DATA SCIENCE & ML EXECUTIVE",
    },
    es: {
        nav_about: "Sobre Mí",
        nav_portfolio: "Portafolio",
        drop_dashboard: "Dashboard",
        drop_ml: "Machine Learning",
        drop_dl: "Deep Learning",
        drop_genai: "GenAI",
        nav_home: "Inicio",
        nav_contact: "Contáctame",
        hero_title_1: "Hola, soy",
        hero_title_2: "Marcos C. Lisboa",
        hero_desc: "Los datos son la espada del siglo XXI, y quien logre manejarlos será el Samurai.",
        hero_hire: "Stack",
        hero_roles: "Científico de Datos, Ingeniero de IA, Analista de Datos, Ingeniero de Datos",
        exp_badge: "Del insight a la producción",
        proj_title: "Últimos Proyectos",
        proj_all: "Todos los proyectos",
        page_title_dashboard: "Proyectos de Dashboard",
        page_title_ml: "Proyectos de Machine Learning",
        page_title_dl: "Proyectos de Deep Learning",
        page_title_genai: "Proyectos de GenAI",
        footer_social: "Redes Sociais",
        footer_email: "Hable conmigo",
        stack_title: "Tech Ecosystem",
        stack_subtitle: "Herramientas que impulsan el impacto de los datos",
        sobre_title: "El Propósito",
        sobre_desc: "Científico de Datos movido por la curiosidad e enfocado em transformar información bruta em soluciones estratégicas. Descubro las historias ocultas en los números para apoyar decisiones de alto valor y generar impacto real.",
        sobre_arsenal: "Arsenal Técnico",
        sobre_arsenal_desc: "Combino programación avanzada, estadística y modelado predictivo para responder a preguntas complejas de negocios de principio a fin.",
        sobre_alem: "Más allá de los Datos",
        sobre_alem_desc: "Mantengo fuertemente el equilibrio entre la vida tech, los deportes, la música y la literatura. Estas experiencias plurales oxigenan mi diseño y aseguran la creatividad profesional.",
        proj_pred: "Predicción de Series Temporales",
        proj_recom: "Sistema de Recomendación",
        proj_fraud: "Detección de Fraudes (Random Forest)",
        proj_yolo: "Detección de Objetos (YOLOv8)",
        proj_med: "Clasificación de Imágenes Médicas",
        proj_nlp: "Procesamiento de Lenguaje Natural",
        proj_rag: "Sistema RAG p/ Documentos",
        proj_assist: "Asistente Virtual Corporativo",

        // Dashboards
        dash_trade_title: "📈 Trade Marketing Analytics",
        dash_trade_subtitle: "Venta al por menor y E-commerce | Trade Mania",
        dash_trade_desc: "Panel completo de análisis de PDV con enfoque en disponibilidad, índice de ruptura e monitoreo de precios promedio por región.",
        dash_trade_feat1: "Disponibilidad e índice de ruptura.",
        dash_trade_feat2: "Precio promedio comparativo por estado.",
        dash_trade_feat3: "Rendimiento del equipo de promotores.",

        dash_health_title: "🩺 Health Data Analytics",
        dash_health_subtitle: "Siniestros Hospitalarios | Desempeño de Planes",
        dash_health_desc: "Monitoreo completo de costos de siniestros de salud, rendimiento de autorizaciones y análisis de coparticipación y procedimientos médicos.",
        dash_health_feat1: "Control financiero sobre R$ 108 mil em procedimentos.",
        dash_health_feat2: "Eficiencia con una tasa de aprobación general del 95%.",
        dash_health_feat3: "Estacionalidad para anticipación de costos de salud.",

        dash_logistics_title: "🌍 Logistics & Supply Chain",
        dash_logistics_subtitle: "Desempeño Macro • Rentabilidad • Riesgos",
        dash_logistics_desc: "Monitoreo global de la cadena de suministro, analizando el crecimiento de ventas (R$ 12.6 Mi) e la eficiencia de envío.",
        dash_logistics_feat1: "Rendimiento Macro: Volumen y rentabilidad por región.",
        dash_logistics_feat2: "Alerta de Pérdida: Detección de cuellos de botella logísticos.",
        dash_logistics_feat3: "Sustento de Beneficios: Enfoque en clientes de alto CLV.",

        dash_ecommerce_title: "🛒 E-commerce Analytics",
        dash_ecommerce_subtitle: "Ventas • Rendimiento • Productos",
        dash_ecommerce_desc: "Panel de monitoreo de ventas en línea, facturación, ticket promedio y rendimiento de productos y categorías.",
        dash_ecommerce_feat1: "Facturación: Análisis de ingresos y ticket promedio.",
        dash_ecommerce_feat2: "Productos: Top productos y categorías más vendidas.",
        dash_ecommerce_feat3: "Clientes: Comportamiento y retención de usuarios.",

        // Web Dashboards - Health
        health_web_title: "Health Data Analytics",
        health_web_subtitle: "Visión Operadora • Gestión de Autorizaciones de Siniestros",
        health_web_filter: "Filtrando por:",
        health_web_kpi1: "Tasa de Aprobación",
        health_web_kpi1_sub: "Desviación mínima de aprobaciones",
        health_web_kpi2: "Valor Total Autorizado",
        health_web_kpi2_sub: "Distribuido en 22 siniestros",
        health_web_kpi3: "Costo Promedio Quirúrgico",
        health_web_kpi3_sub: "Atención Crítica: Principal Ofensor",
        health_web_kpi4: "Ahorro/Reducción",
        health_web_kpi4_sub: "En 3 siniestros reducidos (~27%)",
        health_web_chart1: "Valor Autorizado por Mês",
        health_web_chart2: "Distribución del Costo por Plan",
        health_web_chart3: "Gastos por Categoría de Procedimiento",
        health_web_chart4: "Detalle de Costos por Usuario",
        health_web_insight_title: "Insights y Acciones Estratégicas",
        health_web_discovery: "Principais Hallazgos:",
        health_web_insight_1: "<strong>Tendencias de Gasto:</strong> Buena tasa de aprobación, pero preste atención a las pequeñas reducciones de costos e investigue el motivo. Mejorando el proceso.",
        health_web_insight_2: "<strong>Procedimientos e Prestadores:</strong> Los \"Procedimientos Quirúrgicos\" son los mayores ofensores. Monitorear de cerca el Hospital Santa Cruz y la Clínica Checkup.",
        health_web_insight_3: "<strong>Evaluación de Usuarios Críticos:</strong> El beneficiario 'Carlos Souza' representa el mayor costo aislado. Los casos complejos requieren un seguimiento de salud dedicado.",
        health_web_action: "Plan de Acción Recomendado:",
        health_web_recom_1_title: "Auditoría Centrada en Cirugías",
        health_web_recom_1_desc: "Concentrar la auditoría técnica de salud en las solicitudes quirúrgicas de los mayores proveedores.",
        health_web_recom_2_title: "Gestión de Casos Críticos",
        health_web_recom_2_desc: "Crear un comité para usuarios de uso continuo/complejo como el paciente 'Carlos Souza'.",
        health_web_recom_3_title: "Análisis de Negativas/Reducciones",
        health_web_recom_3_desc: "Revisar los patrones de denegación de reclamaciones y buscar una conciliación proactiva con las clínicas.",

        // Web Dashboards - Trade
        trade_web_title: "Panel de Disponibilidad y Ruptura",
        trade_web_subtitle: "Análisis de cobertura de PDV, evolución de rupturas y precios promedio",
        trade_web_kpi1: "Disponibilidad General",
        trade_web_kpi2: "Ruptura Promedio",
        trade_web_kpi3: "Visitas Realizadas",
        trade_web_kpi4: "PDV Visitados",
        trade_web_kpi5: "Precio Promedio General",
        trade_web_kpi6: "Total de Productos",
        trade_web_chart1: "Productos Indisponibles (evolución)",
        trade_web_chart2: "Rupturas por Categoria (unidades)",
        trade_web_chart3: "Precio Promedio por UF",
        trade_web_chart_desc1: "Descenso gradual tras el pico de agosto → septiembre/octubre con mejora",
        trade_web_chart_desc2: "El chocolate 60% y la barra lideran la falta de disponibilidad",
        trade_web_chart_desc3: "Variación de hasta un 70% por encima de la media general",
        trade_web_top_pdv: "PDV con mayor precio promedio",
        trade_web_performance_title: "Rendimiento por Promotor (Ruptura %)",
        trade_web_insight_1: "Las rupturas cayeron de 125 (ago) a 96 (oct) – tendencia positiva, pero siguen siendo altas en chocolates (60% y barras).",
        trade_web_insight_2: "Variación de precio entre estados: RJ (R$6,60) > MG (R$6,35) > SP (R$6,11). Revisar la política de precios para igualar la competitividad.",
        trade_web_recom_title: "Recomendaciones Estratégicas",
        trade_web_recom_1: "Meta de disponibilidad >70%",
        trade_web_recom_2: "Capacitar a promotores críticos",
        trade_web_recom_3: "Revisar precios por UF",
        trade_web_next_steps: "Próximos pasos:",
        trade_web_next_desc: "Enfoque en chocolate 60% y barras (80% de las rupturas). Auditoría en los PDV con >70% de ruptura. Igualar precio medio entre RJ y SP para reducir canibalización.",

        // Web Dashboards - Logistics
        logistics_web_title: "Análisis de Logística y Cadena de Suministro",
        logistics_web_subtitle: "Rendimiento Macro • Rentabilidad • Riesgos",
        logistics_web_kpi1: "Ingresos Totales",
        logistics_web_kpi2: "Margen de Beneficio",
        logistics_web_kpi3: "Tiempo Promedio de Envío",
        logistics_web_kpi4: "Cant. de Ventas (Volumen)",
        logistics_web_chart1: "Evolución de Ventas Anuales",
        logistics_web_chart2: "Ingresos por Categoría de Producto",
        logistics_web_chart3: "Dominio Regional",
        logistics_web_chart4: "Alerta de Pérdida (Detractores)",
        logistics_web_insight_title: "Conclusiones Estratégicas",
        logistics_web_discovery_title: "Paneles Integrados:",
        logistics_web_insight_1: "<strong>Mercado y Consumidor:</strong> \"Consumer\" representa la mayor parte de los ingresos. Operación B2C masiva y fragmentada.",
        logistics_web_insight_2: "<strong>Estrellas vs. Detractores:</strong> Los equipos de alta tecnología (Copiadoras/Smartphones) mantienen el beneficio. Las mesas y escáneres grandes generan cuellos de botella en el transporte.",
        logistics_web_insight_3: "<strong>Concentración de Valor:</strong> Regla de Pareto aplicada a los 10 principales clientes: necesidad de proteger el valor de vida del cliente (CLV).",
        logistics_web_action_title: "Próximos Desafíos:",
        logistics_web_recom_1_title: "Optimización del Mix (Bottom 10)",
        logistics_web_recom_1_desc: "Revisión de artículos donde el transporte es un ofensor: considerar existencias locales o ajustes de precios de envío.",
        logistics_web_recom_2_title: "Foco en APAC",
        logistics_web_recom_2_desc: "Consolidar las inversiones en Asia-Pacífico, que presenta la mejor relación entre volumen y margen.",
        logistics_web_recom_3_title: "Gestión de Grandes Cuentas",
        logistics_web_recom_3_desc: "Servicio diferenciado para los principales clientes identificados, garantizando la recurrencia de beneficios de alto margen.",

        // Web Dashboards - Ecommerce
        ecom_web_tab1: "📊 Análisis de Ventas",
        ecom_web_tab2: "🌍 Visão Geográfica",
        ecom_web_kpi_profit: "Beneficio",
        ecom_web_chart1: "Ventas Mensuales",
        ecom_web_chart2: "Costo de Envío por Cliente",
        ecom_web_chart3: "Venta por Cliente",
        ecom_web_insight_title: "Insights y Acciones Estratégicas",
        ecom_web_discovery: "Principais Hallazgos:",
        ecom_web_insight_1: "<strong>Estacionalidad Positiva:</strong> Las ventas crecen considerablemente en la segunda mitad de cada año, lo que indica un éxito continuo en las campañas de fin de año.",
        ecom_web_insight_2: "<strong>Alto Costo de Envío:</strong> Ciertos clientes de los segmentos de Consumo y Corporativo generan altos costes logísticos que reducen el margen de beneficio.",
        ecom_web_insight_3: "<strong>Productos Críticos:</strong> Las categorías de ventas críticas tienen un beneficio neto bajo en comparación con el volumen transaccionado.",
        ecom_web_action: "Plan de Acción Recomendado:",
        ecom_web_recom_1_title: "Preparación para el Q4",
        ecom_web_recom_1_desc: "Anclar el stock e realizar campañas masivas de marketing entre octubre e diciembre para maximizar los ingresos de la temporada alta.",
        ecom_web_recom_2_title: "Auditoría Logística",
        ecom_web_recom_2_desc: "Analizar las rutas de envío con mayores costes e renegociar las tarifas o establecer un valor mínimo para el envío gratuito.",
        ecom_web_recom_3_title: "Fidelización B2C",
        ecom_web_recom_3_desc: "Lanzar un programa de recompensas centrado en el segmento de Consumidores (que es mayoritario) para estimular el ticket medio.",
        ecom_web_kpi_sales: "Ventas",
        ecom_web_kpi_orders: "Pedidos Gerados",
        ecom_web_kpi_products: "Total Productos",
        ecom_web_kpi_sales_vol: "Total Ventas Realizadas",
        ecom_web_kpi_customers: "Clientes",
        ecom_web_chart_state: "Recuento de Pedidos por Estado",
        ecom_web_chart_city: "Recuento de Pedidos por Ciudad",
        ecom_web_chart_country: "Ventas por País",
        ecom_web_th_country: "País",
        ecom_web_th_state: "Estado",
        ecom_web_th_city: "Ciudad",
        ecom_web_th_profit: "Suma de Beneficio",
        ecom_web_th_sales_val: "Suma de Valor Venta",
        ecom_web_th_qty: "Cant.",
        ecom_web_filter_all: "Todos",
        ecom_web_filter_high: "Alto",
        ecom_web_filter_low: "Bajo",
        ecom_web_filter_critical: "Crítico",
        ecom_web_filter_medium: "Medio",
        ecom_web_filter_consumer: "Consumidor",
        ecom_web_filter_corporate: "Corporativo",
        ecom_web_filter_others: "Otros",
        ecom_web_filter_office: "Mat. de Oficina",
        ecom_web_filter_furniture: "Muebles",
        ecom_web_filter_tech: "Tecnología",
        ecom_web_filter_prior: "Prioridad Pedido",
        ecom_web_filter_seg: "Segmento",
        ecom_web_filter_cat: "Categoría",
        ecom_web_filter_year: "Año",
        global_days: "días",
        global_thousand: "Mil",
        global_filtering_by: "Filtrando por:",
        trade_web_kpi1_sub: "por debajo del ideal",
        trade_web_kpi2_sub: "promedio por visita",
        trade_web_kpi3_sub: "total en el periodo",
        trade_web_kpi4_sub: "cobertura total",
        trade_web_kpi5_sub: "variación:",
        trade_web_kpi6_sub: "verificados en visitas",
        logistics_web_kpi4_val: "178 Mil",
        health_web_jan_may: "Ene-May 2024",

        // Trade dashboard extras
        trade_web_insight_0: "Disponibilidad general en <strong>43,6%</strong> – muy por debajo del ideal. Aumentar a ≥70% puede generar +30% en ventas en los PDV.",
        trade_web_th_promoter: "Promotor",
        trade_web_th_stockout: "Ruptura (%)",
        trade_web_th_status: "Estado",
        trade_web_status_critical: "crítico",
        trade_web_status_alert: "alerta",
        trade_web_status_warning: "atención",
        trade_web_status_ok: "ok",
        trade_web_training_tip: "📌 El entrenamiento enfocado en los 3 promotores puede reducir la ruptura general hasta 0,2 p.p.",
        trade_web_pdv_sample_title: "Ruptura por PDV (%) – Muestra",
        trade_web_sample_note: "*Datos basados en capturas de pantalla – ruptura superior al 50% indica falla crítica de abastecimiento.",

        // Health dashboard extras
        health_web_th_user: "Nombre del Usuario",
        health_web_th_state: "Estado",
        health_web_th_authorized: "Valor Autorizado",
        health_web_th_reduced: "Valor Reducido",

        // Logistics dashboard extras
        logistics_web_kpi1_sub: "Trayectoria de Crecimiento Exponencial",
        logistics_web_kpi2_sub: "Estabilidad Comprobada",
        logistics_web_kpi3_sub: "Benchmark Logístico",
        logistics_web_kpi4_sub: "Agilidad en Alto Volume",
        logistics_web_detractors_note: "Los costos operativos y logísticos superan el margen.",
        logistics_web_th_product: "Producto / Subcategoría",
        logistics_web_th_cost_type: "Tipo de Costo Elevado",
        logistics_web_th_margin: "Margen Neto",
        logistics_prod_1: "Mesas y Equipos Pesados",
        logistics_prod_2: "Impresoras 3D Específicas",
        logistics_prod_3: "Escáneres de Gran Tamaño",
        logistics_prod_4: "Sillas Ejecutivas",
        logistics_cost_1: "Flete Extra",
        logistics_cost_2: "Costo Operacional",
        logistics_cost_3: "Flete + Descuentos",
        logistics_cost_4: "Flete Voluminoso",

        // Fraud ML Project
        proj_fraud_ml_title: "💳 Detección de Fraudes",
        proj_fraud_ml_subtitle: "Machine Learning en Transacciones Financieras",
        proj_fraud_ml_desc: "Desarrollo de un modelo predictivo para detectar fraudes en tarjetas de crédito, utilizando técnicas de equilibrio (RUS), ajuste de hiperparámetros y optimización de umbral.",
        proj_fraud_ml_results: "84% de Detección • AUC 0.97",
        proj_fraud_ml_problem_title: "Problema de Negocio",
        proj_fraud_ml_problem_text: "Los fraudes representan un riesgo crítico. El desafío es clasificar transacciones en un escenario altamente desequilibrado (0.17% de fraudes), minimizando pérdidas financieras.",
        proj_fraud_ml_objective_title: "Objetivo",
        proj_fraud_ml_objective_text: "Construir un pipeline robusto capaz de detectar fraudes con un alto recall, minimizar falsos negativos y optimizar el umbral de decisión para el impacto empresarial.",
        proj_fraud_ml_pipeline_title: "Pipeline de Machine Learning",
        proj_fraud_ml_metrics_title: "Métricas de Evaluación",
        proj_fraud_ml_impact_title: "Impacto en el Negocio",
        proj_fraud_ml_impact_text: "Transición de una detección reactiva a una proactiva, permitiendo reducir pérdidas financieras y ajustar la sensibilidad según la estrategia de riesgo.",
        proj_fraud_ml_tech: "Python • Scikit-learn • Pandas • Matplotlib",
        proj_fraud_ml_dataset_title: "📊 Dataset",
        proj_fraud_ml_dataset_text: "Dataset de transacciones reales (titulares europeos) con 284.807 registros y solo 492 casos de fraude (~0.17%). Variables transformadas vía PCA.",
        proj_fraud_ml_pipeline_step1: "1. Preprocesamiento",
        proj_fraud_ml_pipeline_desc1: "Normalización y estandarización de variables temporales y financieras mediante StandardScaler.",
        proj_fraud_ml_pipeline_step2: "2. Equilibrio",
        proj_fraud_ml_pipeline_desc2: "Análisis riguroso de técnicas de equilibrio: Random Under Sampling (RUS) vs SMOTE.",
        proj_fraud_ml_pipeline_step3: "3. Modelado",
        proj_fraud_ml_pipeline_desc3: "Regresión Logística y Árboles de Decisión con ajuste de hiperparámetros.",
        proj_fraud_ml_impact_kpi: "Proactivo",
        proj_fraud_ml_github: "Ver en GitHub",
        proj_fraud_ml_other_desc1: "Análisis de tendencias históricas y previsión de la demanda futura.",
        proj_fraud_ml_other_desc2: "Filtrado colaborativo para personalizar la experiencia del usuario.",
        explorer_title_tag: "Sigue Explorando",
        explorer_title_main: "Otros Proyectos de Machine Learning",
        explorer_dash_title: "Business Dashboards",
        explorer_dash_desc: "Visualización estratégica de datos y KPIs de negocio.",
        card_btn_details: "Ver detalles",
        card_btn_view: "Ver dashboard",
        footer_rights: "© 2024 MARCOS C. LISBOA • DATA SCIENCE & ML EXECUTIVE",
    }
};

// ---- Currency Conversion System ----
const CURRENCY_CFG = {
    pt: { symbol: 'R$', rate: 1,    locale: 'pt-BR' },
    en: { symbol: '$',  rate: 0.18, locale: 'en-US' },
    es: { symbol: '€',  rate: 0.16, locale: 'es-ES' }
};

/**
 * Converts a BRL value to the target language currency and formats it.
 * @param {number} brlValue  Original value in BRL
 * @param {string} lang      'pt' | 'en' | 'es'
 * @param {object} [opts]    { short: bool, decimals: number }
 */
function fmtCurrency(brlValue, lang, opts) {
    const cfg  = CURRENCY_CFG[lang] || CURRENCY_CFG.pt;
    const val  = brlValue * cfg.rate;
    const shrt = opts && opts.short;
    const decs = (opts && opts.decimals != null) ? opts.decimals : 2;
    if (shrt && Math.abs(val) >= 1000000) return cfg.symbol + ' ' + (val / 1000000).toFixed(2) + ' Mi';
    if (shrt && Math.abs(val) >= 1000)    return cfg.symbol + ' ' + (val / 1000).toFixed(1) + 'k';
    return cfg.symbol + ' ' + val.toLocaleString(cfg.locale, { minimumFractionDigits: decs, maximumFractionDigits: decs });
}

/** Updates all [data-currency-brl] elements on the page */
function updateCurrencies(lang) {
    document.querySelectorAll('[data-currency-brl]').forEach(function(el) {
        var brl  = parseFloat(el.getAttribute('data-currency-brl'));
        var shrt = el.hasAttribute('data-currency-short');
        var decs = el.hasAttribute('data-currency-decimals') ? parseInt(el.getAttribute('data-currency-decimals')) : 2;
        el.textContent = fmtCurrency(brl, lang, { short: shrt, decimals: decs });
    });
}

function setLang(lang) {
    // 1. Atualizar conteúdo de texto
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });

    // 2. Atualizar moedas
    updateCurrencies(lang);

    // 3. Atualizar estado visual dos botões
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
    });
    const activeBtn = document.getElementById('btn-' + lang);
    if (activeBtn) {
        activeBtn.classList.add('active');
    }

    // 4. Salvar a preferência no cache do navegador
    localStorage.setItem('portfolio_lang', lang);
    
    // 5. Notificar iframes se existirem
    const iframes = document.querySelectorAll('iframe');
    iframes.forEach(iframe => {
        try {
            iframe.contentWindow.postMessage({ type: 'setLang', lang: lang }, '*');
        } catch (e) {
            console.error('Erro ao notificar iframe:', e);
        }
    });

    // 6. Notificar outros scripts que o idioma mudou
    window.dispatchEvent(new CustomEvent('langChanged', { detail: { lang: lang } }));
}

// Quando a página carrega, carregar o último idioma ou o Português como padrão.
document.addEventListener('DOMContentLoaded', () => {
    // Verificar se há um parâmetro 'lang' na URL (comum para iframes)
    const urlParams = new URLSearchParams(window.location.search);
    const langParam = urlParams.get('lang');
    
    const savedLang = langParam || localStorage.getItem('portfolio_lang') || 'pt';
    setLang(savedLang);
});

// Listener para mensagens (para receber do pai se for iframe)
window.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'setLang') {
        setLang(event.data.lang);
    }
});
